DROP TABLE IF EXISTS STUDENTS;

CREATE TABLE STUDENTS (
	ID			SERIAL		PRIMARY KEY,
	NAME		VARCHAR(50) NOT NULL,
	LAST_NAME	VARCHAR(50) NOT NULL,
	AGE			INT			NOT NULL,
	DEGREE		VARCHAR(50)	NOT NULL
);

INSERT INTO STUDENTS (NAME, LAST_NAME, AGE, DEGREE) VALUES 
	('PEDRO', 'ALCANTARA', 45, 'ING. INDUSTRIAL'),
	('LAZARO', 'ALMUDIO', 18, 'ING. AGRICOLA'),
	('MARTIN', 'ROSALES', 26, 'ING. EN SISTEMAS');

SELECT * FROM STUDENTS;


