DROP TABLE IF EXISTS STUDENTS;

CREATE TABLE STUDENTS (
	ID			SERIAL		PRIMARY KEY,
	NAME		VARCHAR(50) NOT NULL,
	LAST_NAME	VARCHAR(50) NOT NULL,
	AGE			INT			NOT NULL,
	DEGREE		VARCHAR(50)	NOT NULL
);
